spring:
  profiles:
    include: db
  #datasource:
    #url:
    #username:
    #password:
    #driver-class-name:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

